version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-firefox_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/firefox:145.0.2@sha256:2fd15a93b177b2079dc14bf7db3ee275ceabec7179d49ad3e4ca9b9595d5101f
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"