version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-firefox_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/firefox:144.0.2@sha256:20e6fa522c9bb19bf4f56ee81a8ce31f8bb6bd2c019fdaff87d074fb75c9c43a
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"