version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibynx-firefox_server_1
      APP_PORT: 3000

  server:
    image: tibynx/firefox:146.0.1@sha256:9be7f3f209392df66c990e7460de0896e64cf32c56159d284fffe98bfb8bc387
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"