version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibynx-firefox_server_1
      APP_PORT: 3000

  server:
    image: tibynx/firefox:151.0.3@sha256:d82143d1184b65112eb358b8e2d791018b24095829bc3df790477fb5f505ad85
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"