version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibynx-firefox_server_1
      APP_PORT: 3000

  server:
    image: tibynx/firefox:153.0.1@sha256:e066ffe042fa99a6041386b1ded83407ad46a05c8c6333e9b584b6d21f5f0022
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"