version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibynx-brave_server_1
      APP_PORT: 3000

  server:
    image: tibynx/brave:1.90.128@sha256:eaab591c8c3eebc6e41ffa763e75afbae8c8149e0a041b6f4c4209067bb3052a
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    security_opt:
      - no-new-privileges:true
    ports:
      - 3577:3001
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"