version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibynx-brave_server_1
      APP_PORT: 3000

  server:
    image: tibynx/brave:1.88.136@sha256:24d40905f67c3cac306c548cea0c64bc82de9dfc48093541bb0178c338f5f444
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    security_opt:
      - no-new-privileges:true
    ports:
      - 3577:3001
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"