version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibynx-brave_server_1
      APP_PORT: 3000

  server:
    image: tibynx/brave:1.93.129@sha256:2738addb6a9b0c99d7367913cf7bfbe766216b06f29c164ca764477efdbd5c4d
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    security_opt:
      - no-new-privileges:true
    ports:
      - 3577:3001
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"