version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibynx-code-server_server_1
      APP_PORT: 8443

  server:
    image: lscr.io/linuxserver/code-server:4.113.0@sha256:629232bdd99640dd3d514a40c740a9d42dcb808a844005821b2f4be6e6a8b66e
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DEFAULT_WORKSPACE=/config/workspace
      - PWA_APPNAME=code-server
