version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibynx-code-server_server_1
      APP_PORT: 8443

  server:
    image: lscr.io/linuxserver/code-server:4.131.0@sha256:621d47575a19645f4267f68a77167ca0b4562d042717dbe0dbba318c9753bad7
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DEFAULT_WORKSPACE=/config/workspace
      - PWA_APPNAME=code-server
