version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibynx-zorinos-core_server_1
      APP_PORT: 3000

  server:
    image: tibynx/webtop:zorinos-core-20260101-223348@sha256:2a37cd6041bd1020fcba81152ebb6481ae75158b048b5069e6928a3379fd36c7
    security_opt:
      - seccomp:unconfined
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"